# Generated by Django 3.1 on 2021-02-06 10:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('museum', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='column',
            name='genre_of_column',
            field=models.ManyToManyField(to='museum.GenreOfColumn'),
        ),
    ]
