# Generated by Django 3.1 on 2020-08-29 13:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('museum', '0002_auto_20200828_1655'),
    ]

    operations = [
        migrations.CreateModel(
            name='Genre',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, null=True)),
            ],
        ),
        migrations.RemoveField(
            model_name='post',
            name='artist',
        ),
        migrations.CreateModel(
            name='Artist',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, null=True)),
                ('genre', models.ManyToManyField(to='museum.Genre')),
            ],
        ),
        migrations.AddField(
            model_name='post',
            name='artist',
            field=models.ManyToManyField(to='museum.Artist'),
        ),
    ]
