# Generated by Django 3.1 on 2020-08-29 13:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('museum', '0003_auto_20200829_2212'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='year',
            field=models.IntegerField(null=True),
        ),
    ]
