# Generated by Django 3.1 on 2020-09-01 03:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('museum', '0006_auto_20200901_1237'),
    ]

    operations = [
        migrations.RenameField(
            model_name='post',
            old_name='artist',
            new_name='artists',
        ),
    ]
