# Generated by Django 3.1 on 2020-09-07 05:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('museum', '0010_column'),
    ]

    operations = [
        migrations.AddField(
            model_name='column',
            name='html',
            field=models.BooleanField(default=False),
        ),
    ]
